version: '3'

services:
  # loopback api service
  api:
    user: "${UID}:${GID}"
    # image: artisin/loopback-dev
    build:
      context: ./dev-images/loopback
      dockerfile: Dockerfile
    # map port 3000 to local 3002
    ports:
      - 3002:3002
      # Debug port
      # - 9229:9229
    # mount current dir to images /usr/src/api
    volumes:
      - .:/usr/src/api
    # watch  changes and restart app
    command: nodemon --ignore 'client/' .

    restart: always
    # degug command
    # command: nodemon --ignore 'client/' -L --inspect ./server

  # mysql database -> https://hub.docker.com/_/mysql/
  mysqlDb:
    image: mysql:5.6
    # environment variables for setup
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PWD}"
    # default MySQL port
    ports:
      - 3306:3306
    # create and map separate volume
    volumes:
      - loopbackDev:/var/lib/mysql
  loadbalancer:
      build: load-balancer
      tty: true
      links:
      - api
      ports:
      - '8080:8080'

# volumes
volumes:
  # mysql
  loopbackDev:
